name: GH secrets
on:
  schedule:
    - cron: "0 4 * * *" 
  workflow_dispatch:


jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Create .env file
        run: |
          echo BOT_TOKEN=${{ secrets.BOT_TOKEN }} >> .env
          echo CHAT_ID=${{ secrets.CHAT_ID }} >> .env

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
          
      - name: Commit and push changes
        run: |
          git config --global user.email "abduegi8@gmail.com"
          git config --global user.name "reginaAbdu"
          git add logs.txt
          git commit -m "update logs"
          git pull origin main --rebase
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
